apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-matcher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-matcher
  template:
    metadata:
      labels:
        app: resume-matcher
    spec:
      containers:
      - name: resume-matcher
        image: resume-matcher:latest
        ports:
        - containerPort: 8000